[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["John Doe <john@example.com>"]
description = "Non-package root monorepo project"
name = "mono-root"
package-mode = false
version = "0.0.1"

[tool.poetry.dependencies]
lib-a = {path = "lib-a", develop = true}
lib-b = {path = "lib-b", develop = true}
python = "^3.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"

[tool.poetry-monorepo.deps]
